version: '3.8'
services:
  db:
    image: postgres:15
    container_name: finance_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: finance_data
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data